### ISSUE TITLE
Support for blob encryption/decryption in V10?

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-storage-java#398] opened 2018-11-02 01:32 UTC
Version 8 of the SDK has support for encrypting a blob before uploading and decryption upon download by setting `BlobEncryptionPolicy` in `BlobRequestOptions`. Will this be added to V10?

**Comment by seguler** [comment] 2018-11-02 06:32
Hi @SukruthKS -

Thanks for raising this. It is in our backlog. Are you currently using the encryption feature ? If so, is there a reason why Https + [Storage encryption at rest](https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption) is not enough ? We don't have many users using the client side encryption given there is encryption on the service, hence we are curious to know more about the reason. Please e-mail azurestoragefeedback@microsoft.com if you prefer to share in confidence.

**Comment by SukruthKS** [comment] 2018-11-02 21:51
Yes, we are currently using the client side encryption feature. The keys for encryption are provided by our customers and they are not necessarily stored in Key Vault. Also, different paths in the storage account will typically have different keys. So server side encryption will not cover all our scenarios. We also just had a meeting with some folks from the storage team and brought this up. Hope the support for client side encryption gets added to V10 soon.

**Comment by rickle-msft** [comment] 2019-04-08 22:39
@SukruthKS as a quick update, we are in the final stages of development for this feature with a release hopefully following suit shortly thereafter. I will update here again as the process progresses.

**Comment by SukruthKS** [comment] 2019-04-08 22:41
Thank you @rickle-msft !

**Comment by sid374** [comment] 2019-06-27 01:55
@rickle-msft which release is this feature slated for? We also use the client side encryption available in V8 and are planning on moving to the the new V11 SDK. However, the lack of client-side encryption could be a blocker for us.

**Comment by rickle-msft** [comment] 2019-06-27 17:20
@sid374 Unless you are interested specifically in the async features of v11, I would actually advise that you wait on your upgrade for right now and stay on v8, which is still actively supported. Given the feedback we've received, we are both reworking the network stack to add a lot more stability and resiliency and adding a better story for customers who want to continue to use sync operations. The async concepts will still be comparable to what we have now, which is why it might be worth starting to play around with v11 if that's what you're interested in, but otherwise I think waiting a couple weeks for some more information is a safer bet.

**Comment by sid374** [comment] 2019-06-27 20:05
@rickle-msft Thanks for the input! 

We do not need to use the asynchronous features of the library. The only motivation for upgrading was taking advantage of new features announced recently (like uploading directly to the archive tier). Will you guys be adding synchronous APIs to the the next version as well?

**Comment by rickle-msft** [comment] 2019-06-27 20:16
The new service features will continued to be supported in v8 for the next few releases at least. I actually don't have information on exactly what the messaging is, but I know that, given the difficulties we've been having with v10/11, we're not going to pressure people to upgrade by deprecating the old version until the newer version is more mature and has proven to be more stable than it is now. We're not going to leave you guys with no good options. 

I can confirm that there will be sync APIs in the next version. AsyncIO will still be supported as well, but we have noticed that a good number of customers are not interested in/ready for that paradigm, so we are adding sync apis in a way that will remove the need to have a bunch of ugly blockingGet calls everywhere.

**Comment by rickle-msft** [comment] 2019-11-06 18:58
I am going to close this issue as I believe it has been addressed. An encryption package was GAed alongside v12. V12 also supports sync and async apis so customers can pick what suits their application and environment best. Please feel free to reopen or comment if you need further support.

**Closed by rickle-msft** 2019-11-06 18:58 UTC
Labels: v10
