### ISSUE TITLE
Unresolve Class Conflict in : azure-storage-blob 10.3 mixed with azure-storage 8.0

### ISSUE THREAD

**Issue by leoninez** [Azure/azure-storage-java#418] opened 2018-12-22 13:48 UTC
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
azure-storage-blob 10.3 mixed with azure-storage 8.0

### What problem was encountered?
Class conflict for:    com.microsoft.azure.storage.blob.BlobListingDetails
The error message as:

`Type 'com/microsoft/azure/storage/blob/BlobListingDetails' (current frame, stack[3]) is not assignable to 'java/lang/Enum'`

- BlobListingDetails in azure-storage-blob 10.3 is one "final class"
- BlobListingDetails in azure-storage 8.0 is one "enum"

The class com.microsoft.azure.storage.blob.BlobListingDetails shares 100% same name in azure-storage-blob 10.3 and azure-storage 8.0, leading to if ever want to try mixing them will cause this hard-to-resolve problem since we could directly simply exclude the jars as other version conflict does.

I believe it is not wise to use the exactly same class name for one common usage class as BlobListingDetails. At least you should append version control  in the package name, such as:

`com.microsoft.azure.storage.blob.v10.BlobListingDetails`

since azure-storage-blob 10.3 greatly change the programing API for azure storage. 

What is even worse is that, many other open source library, such as Spark 2.4, Hadoop-azure relies on azure-storage library. So I believe in the big-data area, maybe none of  people will use the azure-storage-blob 10.3 since this unresolvable class conflict.

### Have you found a mitigation/solution?

No as long as use azure-storage-blob 10.3 even I could use class loader to isolate the conflict which indeed is troublesome.

So I downgrade to azure-storage 8.0 and do many refine work, wasting a lot of time.

**Comment by rickle-msft** [comment] 2018-12-28 18:31
Hi, @leoninez. Thank you for noting this. This is a duplicate of #400, which is scheduled to be resolved in our next breaking release. I am going to close this issue since we are having this discussion elsewhere, but please feel free to reopen it if you have further concerns or to post a new issue as you see fit.

**Closed by rickle-msft** 2018-12-28 18:31 UTC
