### ISSUE TITLE
are blob input/output streams are deprecated in SDK v10.1.0?

### ISSUE THREAD

**Issue by vamsikt** [Azure/azure-storage-java#369] opened 2018-10-03 13:18 UTC
It looks like blob streams [BlobOutputStream](https://github.com/Azure/azure-storage-java/blob/07fba08e00d3fa29161b8fd9ad0042c5f932cd78/microsoft-azure-storage/src/com/microsoft/azure/storage/blob/BlobOutputStream.java) are not supported in the v10.1.0? Are they deprecated?

**Comment by rickle-msft** [comment] 2018-10-05 18:02
Yes and no. There are no plans to include BlobOutputStream in v10+ of the library, as there were some major architectural changes in this version in an effort to include asynchronous IO. These changes in philosophy and architecture have shifted away from BlobOutputStream and several other patterns in the legacy SDK at least for the reason that the newer versions make use of RxJava and Reactive Streams, which exposes a Flowable type that takes the place of more standard streams. 

That said, v8 is currently still supported and maintained and will be for at least the next six months. BlobOutputStream is therefore not deprecated within the libraries that offer it, and you are encouraged to use it if you are still on versions pre-10. 

Further, we will soon be adding a method to TransferManager in V10 to the effect of uploadFromNonReplayableFlowable. While not a direct analog to BlobOutputStream, it will offer the ability to conveniently upload data from a Flowable of unknown length, which means it can be used for similar scenarios. Uploading from a file and uploading from in memory data are already supported, and I am happy to offer guidance on best practices in the new paradigm if you need.

**Comment by vamsikt** [comment] 2018-10-05 19:58
@rickle-msft thank you for the response and detailed explanation.
Right now we make use of [BlobOutputStream](https://github.com/Azure/azure-storage-java/blob/07fba08e00d3fa29161b8fd9ad0042c5f932cd78/microsoft-azure-storage/src/com/microsoft/azure/storage/blob/BlobOutputStream.java) to write to blob from continuing stream (unknown length).
Is there any functionality in v10 to achieve this or need to wait until we have this new TransferManager function.
`we will soon be adding a method to TransferManager in V10 to the effect of uploadFromNonReplayableFlowable`

**Comment by rickle-msft** [comment] 2018-10-05 20:39
@vamsikt This is the primary scenario for offering this api, and more specifically a network stream (see below). The technical difficulty involved is that we have to set the content-length header up front, but we don't know that until we reach the end of the Flowable. That's why the base apis take in a length parameter. Further, if the Flowable is not replayble (or the "stream" is not seekable), as is the case when coming from network streams, then we run into issues with retries as we don't have a good way to try sending the data again. Therefore, the only way we can reliably get the data up in the case where we don't know the length up front is to do some buffering, which we will make transparent to the user and configurable as well so as not to eat more memory than we should.

Given that information, and to more directly answer your question, the recommended solution for now is to do some buffering yourself; there's not currently another api which will do some part of this for you. Depending on the anticipated size of your stream, you could buffer it all first and then just call upload, or you could implement some sort of chunked buffering logic and send up blocks at a time with a commit block list at the end. I would be happy to discuss this solution with you further while this feature is in development. I would estimate maybe beginning of November for that feature, but I can't make any promises as priorities change regularly depending on what the Storage service itself has coming.

If you are interested:
You can track the feature here: https://github.com/Azure/azure-storage-java/issues/304
And you can see a lengthy discussion on this feature here (it's a bit burried in there after we determine the root cause of that issue, but it's there): https://github.com/Azure/azure-storage-java/issues/344

**Comment by vamsikt** [comment] 2018-10-05 20:58
@rickle-msft for obvious reasons we can't buffer it all and then upload from a file as the data size is quite large, so we make use of output stream.
feature #304 will really help us to have a pipeline that streams the large data to Azure easily instead of dealing with chunked/upload features.

**Comment by rickle-msft** [comment] 2018-10-05 21:37
@vamsikt understandable. I tossed that out for completeness but figured it probably wouldn't work for you guys. Just to be clear, as I mentioned above, the proposed implementation will do some buffering, but it will be configurable by the user so that we don't overwhelm whatever system we're on. Some amount of buffering is necessary for us to support retries, which we believe are inextricable from practices on distributed systems. 

As we have addressed your original concerns and you have another issue to track, I will close this issue, but please feel free to re-open it if you have any more questions. Thank you for your time and feedback.

**Closed by rickle-msft** 2018-10-05 21:37 UTC
