### ISSUE TITLE
Connection Reset by peer while uploading blob with BlobkBlobUrl.upload()

### ISSUE THREAD

**Issue by lagerspetz** [Azure/azure-storage-java#438] opened 2019-02-19 09:37 UTC
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
10.5.0

### What problem was encountered?
I am uploading blobs to save json-formatted text data into Azure Blob Storage. When I run the application overnight, receiving messages about once every 10 minutes, the application stops being able to upload or download data from Azure storage. I also see many "channels leaked" and "Connection reset by peer" messages from the Azure SDK or libraries it uses. I do not have any other version of netty in my app except for the one pulled by `compile group: 'com.microsoft.azure', name: 'azure-storage-blob', version: '10.5.0'`. I use the following code for uploads:

```
	@Override
	public int store(String name, String jsonData) {
		BlockBlobURL blob = containerURL.createBlockBlobURL(name);

		byte[] array = jsonData.getBytes(AuthUtils.utf8);
		ByteBuffer buf = ByteBuffer.wrap(array);
		Flowable<ByteBuffer> data = Flowable.fromArray(buf);
		long length = array.length;
		Single<BlockBlobUploadResponse> resp = blob.upload(data, length);
		BlockBlobUploadResponse result = resp.blockingGet();
		return result.statusCode();
	}
```

The errors I have got are like the following:

```
2019-02-19 02:42:57.239  WARN 9154 --- [ntLoopGroup-1-2] com.microsoft.rest.v2.http.NettyClient   : Error emitted o
n channel 50f0698f. Message: Connection reset by peer
2019-02-19 02:42:57.239  INFO 9154 --- [ntLoopGroup-1-2] c.m.rest.v2.http.SharedChannelPool       : ---- com.micros
oft.rest.v2.http.SharedChannelPool@440fdd18: size 64, keep alive (sec) 300 ----
2019-02-19 02:42:57.239  INFO 9154 --- [ntLoopGroup-1-2] c.m.rest.v2.http.SharedChannelPool       : Channel State
 For     Age     URL
2019-02-19 02:42:57.239  INFO 9154 --- [ntLoopGroup-1-2] c.m.rest.v2.http.SharedChannelPool       : 50f0698f
 AVAIL   184s    184s    https://vesratstorage.blob.core.windows.net:443
2019-02-19 02:42:57.239  INFO 9154 --- [ntLoopGroup-1-2] c.m.rest.v2.http.SharedChannelPool       : Active channels
: 54 Leaked channels: 53
```

### Have you found a mitigation/solution?
No. Restarting the program fixes the issue temporarily.

**Comment by rickle-msft** [comment] 2019-02-19 20:44
Hi, @lagerspetz. Thank you for sharing this information. We are aware of this issue and are actively investigating/working on getting a repro. It looks like from your logs that these events are being recorded, but the exceptions are not bubbling up or interfering with the operation of your application. Is that correct? Or do you eventually see stalls or crashes because of this?

**Comment by lagerspetz** [comment] 2019-02-20 07:06
Thanks for the quick response. The application does stall in the sense that no new azure blob reads or writes get through anymore at that point. This happens at around 100 "leaked channels" as reported by the shared channel pool print. I see also another exception when the application stalls, but it seems to be coming from the Spring framework. I will edit this message to include it soon.

**Comment by rickle-msft** [comment] 2019-02-20 18:03
Hi, @lagerspetz. Can I ask you to re-share this info over on #363, please? After what you shared, it looks like this issue is the same as what those guys are hitting, and it would be best to consolidate the information. I will close this issue as I believe it is a duplicate of the other that we are actively investigating, but be sure we will continue to discuss over there.

**Closed by rickle-msft** 2019-02-20 18:03 UTC
