### ISSUE TITLE
ListBlobs hierarchical sometime returns duplicate folders and/or misses blob entries

### ISSUE THREAD

**Issue by ghooning** [Azure/azure-storage-java#235] opened 2017-11-27 15:26 UTC
Sometimes when I call listBlobs() with parameter useFlatBlobListing set to false, duplicate 
folders are returned and/or not all blobs are returned. E.g.:
		
/container/folder1/blob1
/container/folder1/blob2
/container/folder2/folder3/blob3
/...

Calling listBlobs("container", false, EnumSet.of(BlobListingDetails.METADATA), null, null)
returns :

container/folder1
container/folder1
container/folder2

And a next call to Calling listBlobs("container/folder1", false, EnumSet.of(BlobListingDetails.METADATA), null, null) 
may return:

/container/folder1/blob1

**Comment by jofriedm-msft** [comment] 2017-11-28 15:47
Hi @ghooning , there was a bug on the service where duplicate directories were being listed but this should be fixed now. What version of the library are you using? Can you share a fiddler trace to see what the service is returning? Also, please follow all markers if you weren't previously doing this.

**Comment by ghooning** [comment] 2017-11-29 10:59
Hi jofriedm-msft,
Thanks for the answer. I'm using version 6.1.0. I'm unable to get Fiddler running on my mac. Maybe Wireshark?
I'm not sure what you mean by 'follow all markers'.
Other strange thing I noticed; when I copy the complete Blob Container to another account, rename the original and then restore the original one (using _Microsoft Azure Storage Explorer_), everything is working again...?

**Comment by jofriedm-msft** [comment] 2017-11-30 17:40
Hi @ghooning, we are following up about the duplicate results bug to see if this fix has been rolled out. You don't need to worry about the marker for this API so please disregard that (it is just a continuation token). For the missing blob entries though, this is because you have useFlatListing set to false so the service will only return results up to the first '/'. To see all blobs you will have to set this value to true or else do what you did above and pass in prefixes for virtual folder names.

**Comment by ghooning** [comment] 2017-12-04 07:56
Hi jofriedm-msft,
I know about he useFlatListing parameter but when set to false it also misses some 'real' Blobs sometimes. This only occurred when duplicates are also returned. Maybe it has something to with this problem?

**Comment by jofriedm-msft** [comment] 2017-12-13 17:47
@ghooning , the fix for duplicates was not rolled out and it should be coming soon. You need to set useFlatListing to true in order to see all real Blobs. Can you try setting that and see if you are still missing results and if so share relevant Service request IDs

**Comment by ghooning** [comment] 2017-12-18 07:55
Thanks jofriedm,
Can you give me an estimate on when the fix will be released?
I will try the useFlatListing=true again and see if I can reproduce the problem and let you know my findings.

**Comment by mirobers** [comment] 2017-12-18 16:37
The fix will be rolled out worldwide by the end of January.

There is no known issue where a blob is missing from a listing (with or without useFlatListing). Can you reproduce this behavior and capture client-side logs?

**Comment by ghooning** [comment] 2017-12-20 13:09
Thanks mirobers,
I'll try to reproduce the behavior and let you know if I find the problem again.

**Closed** 2018-08-13 23:32 UTC
