### ISSUE TITLE
Upload Time-out not working, connection hangs indefinitely 

### ISSUE THREAD

**Issue by Darrelk** [Azure/azure-storage-java#78] opened 2016-02-02 11:46 UTC
Hello,

When uploading a file using the Microsoft Azure Storage Client SDK, and the connection takes very long to return, then it will never time out.

Debugged it until this line.
com.microsoft.azure.storage.core.ExecutionEngine:119

`currResult.setStatusCode(request.getResponseCode());`

Possible solution would be to create a monitor thread that can close the connection if there is no response after X seconds.

`request.disconnect();`

**Comment by pemari-msft** [comment] 2016-02-02 16:23
Yes, sometimes connections hang on the network. Have you tried setting BlobRequestOptions.maximumExecutionTimeInMs? This is an overall timeout across retries set up for this scenario.

**Comment by Darrelk** [comment] 2016-02-03 05:38
Yes, tried setting BlobRequestOptions.maximumExecutionTimeInMs, still not working.

Here is a snippet of the code I am using. If the server take longer then 10 seconds to respond, I would like the connection to close, so that the app does not freeze and wait for it to respons indefinitely.

```
BlobRequestOptions blobRequestOptions = new blobRequestOptions.setMaximumExecutionTimeInMs(10000);
blobRequestOptions.setTimeoutIntervalInMs(10000);
blobRequestOptions.setRetryPolicyFactory(new RetryExponentialRetry(10000, 0));

CloudBlockBlob blobBlock = new CloudBlockBlob(uri);
sasBlob.upload(fileInputStream, fileReference.length(), null, blobRequestOptions, null);
```

Maybe you can expose a method that allows me to disconnect the HttpURLConnection myself. I will then run this in a monitoring thread that will disconnect the HttpURLConnection after a few conditions.

**Comment by Darrelk** [comment] 2016-02-03 07:40
Now registering for a  SendingRequestEvent on OperationContext object:

```
final RequestTimeoutThread requestTimeoutThread = new RequestTimeoutThread(this);
OperationContext opContext = new OperationContext();
StorageEventMultiCaster storageEventMultiCaster = new StorageEventMultiCaster<>();
storageEventMultiCaster.addListener(new StorageEvent<SendingRequestEvent>() {

    @Override
    public void eventOccurred(SendingRequestEvent eventArg) {
        HttpURLConnection request = (HttpURLConnection) eventArg.getConnectionObject();
        // Do custom monitoring here...
    }
});
opContext.setSendingRequestEventHandler(storageEventMultiCaster);

blobBlock.upload(fileInputStream, fileReference.length(), null, blobRequestOptions, opContext);
```

I then start a new thread to monitor for activity and if it is dead for to long, I disconnect the HttpURLConnection. This works for me.

**Comment by emgerner-msft** [comment] 2016-02-03 17:57
Great, that is the correct way of doing that. I do want to clarify a couple things just in case to make sure this works as you expect:

1. TimeoutIntervalInMs is sent with each individual service request (upload may do multiple if it has to chunk the data), and MaximumExecutionTimeInMs applies across individual service requests including retries. TimeoutIntervalInMs actually sends a timeout argument to the service which will send a failure if the request cannot be completed in the specified time. MaximumExecutionTime does not create a monitor thread (mainly for perf reasons), it simply adds up the time taken so far once the request fails.

2. The retry policy you set doesn't make sense. It means backoff 10000MS but don't ever attempt to retry. I'm guessing if you have a flaky network you might want to retry at least once. If you don't want to retry at all, simply use RetryNoRetry.

3. It's fine to cut off the request like you're doing above, but take care that some requests may take longer to succeed. If you're done sending data and you close the connection the service may still end up finishing and then simply not be able to respond. So, you might want to consider still setting the timeout, and then give some additional time to allow the service to send a failure or success response. If you don't care whether it succeeds or fails you can skip this, but most people do want to know.

**Comment by Darrelk** [comment] 2016-02-04 04:28
Thanks for the reply. This is certainly a good explanation.

1. I tried using the TimeoutIntervalInMs, still if the server never responds, then it does not time out. To test this, I created a proxy that sleeps for x minutes, thus it will not return anything for x minutes. The connection should then close after xyzMS, but it does not.

2. I will use the RetryNoRetry option. I do the retries on my side so I can log what failed and what is being retried.

3. I am actually using the CloudBlockBlob.uploadBlock() method to upload blob blocks, so I keep track of how many bytes have been uploaded. There is then a monitoring thread that checks for changes and if there were no change for more then x seconds, then I close the connection.

Thanks again for all the help.

**Comment by emgerner-msft** [comment] 2016-02-04 17:41
1. That sounds like the expected behavior. I don't know the exact details of your test, but the server timeout is simply to tell the server when to stop trying to complete the request. It will not close the connection on the client side if the proxy ignored the server response.

2. If that works, great. In case it helps: You can do custom retry policies by implementing the RetryPolicyFactory class to return a custom class extending RetryPolicy. Many folks do this to not only have custom retry scenarios but to do operations such as logging.

3. If that works, great. Again, in case it helps:  Also note the EventHandlers in OperationContext (looks like you already found the SendingRequest one). These will be called once per service call so if you use a convenience API such as upload() you can still access and monitor every service call it makes at key points in its lifecycle.

Glad you got things working! Will close this issue as resolved.

**Closed by emgerner-msft** 2016-02-04 17:41 UTC
