### ISSUE TITLE
New version of storage SDK are not downloadable using maven

### ISSUE THREAD

**Issue by mkozioro** [Azure/azure-storage-java#533] opened 2020-03-18 15:18 UTC
Hi,

After going into https://mvnrepository.com/artifact/com.microsoft.azure/azure-storage, I see that 8.6.1 version of storage sdk was released and packages were relocated to com.azure group.

Unfortunately I can't download it, because of incorrect relocation.
I see change file in https://github.com/Azure/azure-storage-java/blob/legacy-master/ChangeLog.txt

Was this new version of SDKs released?

**Comment by rickle-msft** [comment] 2020-03-18 17:16
@mkozioro @sandrzejczak Thank you guys for reporting this. We were hoping to add some information built into the pom about the presence of v12 in another location, but it seems it didn't quite work as intended and is obstructing proper resolution of this dependency. I'll put out 8.6.2 today and remove this pom element, so things should go back to normal.

**Comment by rickle-msft** [comment] 2020-03-18 21:29
I have just triggered a release of 8.6.2 that should be out shortly and should resolve this issue. I am going to close this issue, but please feel free to reopen it if you continue to experience problems.

**Closed** 2020-03-18 21:30 UTC
