### ISSUE TITLE
Calls to blockingGet() hang

### ISSUE THREAD

**Issue by mattvryan** [Azure/azure-storage-java#449] opened 2019-03-12 17:08 UTC
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
10.5.0

### What problem was encountered?
Any time I call `blockingGet()`, the call hangs and never returns control back to my application.

### Have you found a mitigation/solution?
No

I'm trying to use the new SDK, but anytime I call `blockingGet()` the application hangs.  It doesn't seem to matter what action I take - I've tried creating containers, creating blobs, deleting blobs, etc.  It always hangs in `blockingGet()`.

Here's a very simple sample of what I'm trying to do:

```
SharedKeyCredentials credentials = new SharedKeyCredentials(accountName, accountKey);
ServiceURL serviceURL = new ServiceURL(
    new URL(String.format("http://%s.blob.core.windows.net", accountName)),
    StorageURL.createPipeline(credentials, new PipelineOptions())
);
ContainerURL containerURL = serviceURL.createContainerURL(container);
ContainerCreateResponse rsp = containerURL.create().blockingGet();  // hangs here
```

I've noticed the following behaviors:
- The action I invoke seems to take place.  So in the example above, the container I am trying to create actually does get created.  It appears then that the code is hanging on the response.
- If I step into this with a debugger, `blockingGet()` is waiting on a `Latch`, which is where the hang occurs.

I also get the following stack trace:

```
WARNING: An exception 'java.lang.NoSuchMethodError: com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase.findFormatOverrides(Lcom/fasterxml/jackson/databind/DeserializationContext;Lcom/fasterxml/jackson/databind/BeanProperty;Ljava/lang/Class;)Lcom/fasterxml/jackson/annotation/JsonFormat$Value;' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NoSuchMethodError: com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase.findFormatOverrides(Lcom/fasterxml/jackson/databind/DeserializationContext;Lcom/fasterxml/jackson/databind/BeanProperty;Ljava/lang/Class;)Lcom/fasterxml/jackson/annotation/JsonFormat$Value;
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase.createContextual(JSR310DateTimeDeserializerBase.java:32)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.createContextual(InstantDeserializer.java:227)
	at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:669)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:430)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:947)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:439)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:428)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:947)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:439)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:461)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3838)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3732)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2764)
	at com.microsoft.rest.v2.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:133)
	at com.microsoft.rest.v2.protocol.HttpResponseDecoder.deserializeHeaders(HttpResponseDecoder.java:292)
	at com.microsoft.rest.v2.protocol.HttpResponseDecoder.decode(HttpResponseDecoder.java:66)
	at com.microsoft.rest.v2.policy.DecodingPolicyFactory$DecodingPolicy.lambda$sendAsync$0(DecodingPolicyFactory.java:34)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:76)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:59)
	at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
	at com.microsoft.rest.v2.http.NettyClient$HttpClientInboundHandler.channelRead(NettyClient.java:916)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I suspect there's a JSON deserialization problem in the response parsing that is throwing this exception.  As a result the thread handling the response is crashing and never decrementing the `Latch` and thus the `blockingGet()` never returns.

**Comment by mattvryan** [comment] 2019-03-12 17:10
I looked at #358 which appears similar, but I'm not sure this is the same problem.  I'm not including any Jackson dependencies in my POM, which appeared to be the issue in #358.

**Comment by mattvryan** [comment] 2019-03-12 17:20
My context:  I'm trying to update the Azure support in Apache Jackrabbit Oak (see https://issues.apache.org/jira/browse/OAK-8105), which is an open source implementation of the JCR spec.  Since the JCR spec is synchronous, it seems to me that `blockingGet()` is going to be a requirement for my use.

As a side note, I really would have preferred retaining stream support in the new SDK, as was mentioned in #389.  I get the benefit of async for clients directly using the SDK, but for libraries using the SDK to add Azure support, if the API of those libraries is synchronous, this new SDK just represents a big hurdle to retain Azure support, especially if you have to move to v10 in order to bypass bugs in v8 (like I have to with Apache Jackrabbit Oak).

**Comment by rickle-msft** [comment] 2019-03-12 17:30
Hi, @mattvryan. Could you try swapping out for the older versions of 10.x and see if those encounter the same problem in your context?

Thank you as well for the input on the need for stream support. We are discussing the story for customers who intend to stay in synchronous environments and will take this into consideration.

**Comment by rickle-msft** [comment] 2019-03-12 22:45
I just ran a create container call in a sample application and it worked just fine. It looks like the deserializer is having trouble with something related to DateTimes, which I think would explain why this happens on all requests as all HTTP responses have a date header. 

What version of Java are you using? And what other dependencies do you have in your project?

**Comment by mattvryan** [comment] 2019-03-13 00:05
Hi @rickle-msft , thanks for your help so far.  It looks like it was a dependency problem after all, probably dealing with Jackson as in #358.  So maybe related to #358 after all.  In my case, I wasn't including Jackson directly, but another library was, and the versions were different.  I resolved the issue by manually specifying all the Jackson libraries that I needed and what versions I wanted (latest).  This resolved the issue.

Maybe it had to do with communication between `jackson-datatype-jsr310` and another Jackson package that was being included by the other dependency?  The other dependency was pulling in `jackson-databind` and `jackson-dataformat-cbor`; `jackson-datatype-jsr310` was being pulled in by the Azure SDK of course.

I wonder what you might want to do to help others avoid this in the future, any ideas?  I've spent several days chasing this down; it would be nice if the time spent could help others avoid it in the future. :)

**Comment by mattvryan** [comment] 2019-03-13 00:18
Specifics on the Jackson dependency versions:
- I was including another dependency which eventually included:
  - `jackson-databind` version 2.6.7.2
  - `jackson-dataformat-cbor` version 2.6.7
- Azure Storage SDK v10 for Java eventually included:
  - `jackson-dataformat-xml` version 2.8.11
  - `jackson-datatype-jsr310` version 2.8.11

When I explicitly specified all four packages (version 2.9.8) in my POM the issue went away.

**Comment by atabakatsapcom** [comment] 2019-03-19 16:05
Encountered the same issue using azure-storage-blob: 10.5.0, single thread UPLOAD
In my case it doesnt happen at once, only after a sequence of 
createBlockBlobURL 
followed by calling the corresponding 
.download().blockingGet()

Stacktrace shows the get stuck on 

at jdk.internal.misc.Unsafe.park(java.base@11.0.2/Native Method)
	- parking to wait for  <0x00000006b3c19b20> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.2/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.2/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11.0.2/AbstractQueuedSynchronizer.java:1039)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@11.0.2/AbstractQueuedSynchronizer.java:1345)
	at java.util.concurrent.CountDownLatch.await(java.base@11.0.2/CountDownLatch.java:232)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:85)
	at io.reactivex.Single.blockingGet(Single.java:2807)

**Comment by rickle-msft** [comment] 2019-03-19 17:11
@atabakatsapcom Have you investigated at all whether this comes from a conflict in Jackson dependencies?

**Comment by atabakatsapcom** [comment] 2019-03-20 03:07
![image](https://user-images.githubusercontent.com/43004886/54640032-7bdb5680-4a97-11e9-9a64-68687e0ec6c0.png)

These are the Jackson packages i found in my application Spring Boot Jar . (implicit dependency)
Didnt see any class loading errors / issues

**Comment by mattvryan** [comment] 2019-03-20 03:42
@atabakatsapcom I'd suggest you try specifying latest versions of all of them, like I [mentioned earlier](https://github.com/Azure/azure-storage-java/issues/449#issuecomment-472230850).  In my case, at first I would see it get stuck exactly the same as you showed, waiting for the latch.  It was only after further digging I was able to determine that a background thread was throwing an exception that pointed to the Jackson libraries.  That stack trace never showed up on my console.

If the same thing is happening to you, the background thread might be failing and throwing the exception but you never see it.  If that thread is supposed to decrement the latch which would unblock the wait in `blockingGet()`, that would explain why it hangs, because it is waiting for the latch to decrement by the background thread which never happens because of the exception.

I'd say it's worth a try anyway to see if explicitly setting the versions of the Jackson libraries makes any difference.

**Comment by atabakatsapcom** [comment] 2019-03-20 15:54
Tried, didnt help. mvn dependency:tree shows them as unrelated and at runtime it didnt help.
Migrated back to the com.microsoft.azure:azure-storage:8.0.0  old fashion but seems it works

**Comment by rickle-msft** [comment] 2019-03-20 16:57
@atabakatsapcom I just finished working with another customer that was facing this, and mvn dependency:tree somehow seemed to give inaccurate data indicating all the Jackson versions were the same. It was only after setting an exception breakpoint on the NoSuchMethodError that we were able to confirm the root cause was the same. Point being, it wasn't terribly clear that it was the same issue, but it ended up having the same fix, which I suspect could still be true in your case despite what mvn dependency:tree is showing.

Anyway, if you are more comfortable on v8 right now, that is a perfectly legitimate option

**Comment by rickle-msft** [comment] 2019-11-06 18:48
I am going to close this issue as it seems like it is not active anymore: whether it was resolved or the customers stuck to v8. We also are encouraging people to move to v12 as we are not planning new feature or bug fix releases for v11. Please feel free to reopen or comment if you need further support.

**Closed by rickle-msft** 2019-11-06 18:48 UTC
Labels: v10
