### ISSUE TITLE
Getting error 'An existing connection was forcibly closed by the remote host' using TransferManager.uploadFileToBlockBlob

### ISSUE THREAD

**Issue by infiniti2510** [Azure/azure-storage-java#386] opened 2018-10-21 00:10 UTC
Using the following, I keep seeing connections being forcibly closed by the remote host. 

 TransferManager.uploadFileToBlockBlob(fileChannel, blobURL, 8 * 1024 * 1024, transferManagerUploadToBlockBlobOptions)

content1/contentstore%2F2018%2F10%2F20%2F19%2F54%2F5e2e8fba-7e2f-485e-9722-331e263fba33.bin'==> OUTGOING REQUEST (Try number='1')

ERROR) Unexpected failure attempting to make request.
Error message:'An existing connection was forcibly closed by the remote host'

INFO) 'https://storageaccount.blob.core.windows.net/content1/contentstore%2F2018%2F10%2F20%2F19%2F54%2F5e2e8fba-7e2f-485e-9722-331e263fba33.bin'==> OUTGOING REQUEST (Try number='2')

ERROR) Unexpected failure attempting to make request.
Error message:'An existing connection was forcibly closed by the remote host'

2018-10-20 19:54:53,994  ERROR [azure.adapter.AzureWriteStreamListener] [nioEventLoopGroup-1-13] Failed to upload file with error: {}
 java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:405)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:360)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1396)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.handler.ssl.SslHandler.forceFlush(SslHandler.java:1776)
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:775)
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:752)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:533)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.lambda$writeBodyEnd$4(NettyClient.java:399)
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener$$Lambda$52/1178559056.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rickle-msft** [comment] 2018-10-24 17:02
Hi @infiniti2510. Sorry for the delay. I missed your issue somehow. And thank you for posting this. It looks like this is essentially the same issue as #363. The exception message is different, but the stack trace is almost identical, so I think it is the same root cause. We are actively working on a fix for this and will hopefully have some good results soon.

In the meantime, how often are you seeing this? Typically we see this largely mitigated by retries; a connection is closed, we issue a retry to reestablish a connection, and everything works fine. Do you have retries enabled (they are on by default)?

**Comment by infiniti2510** [comment] 2018-10-29 17:52
Hi, I did see #363 and added the change to the POM to pull in the newer version of com.microsoft.rest.v2 and this helped but didn't totally resolve the issue. We were still seeing this even with retries added. What I found to resolve the issue was to add in newer io.netty libraries, adding an exclusion on the com.microsoft.rest.v2 and adding them back in as dependencies but for version 4.1.30.Final.

**Comment by rickle-msft** [comment] 2018-11-15 00:33
Hi, @infiniti2510. Sorry for the long delay. Have you found that the newer version of netty has totally resolved this issue? Or are you still having some difficulties with the Storage SDK in particular?

**Comment by rickle-msft** [comment] 2019-04-08 17:53
@infiniti2510. We just released v11.0.0 which depends on a new version of the client-runtime. A significant amount of effort went into resolving many of these connection issues. If you are still interested, could you please try upgrading and seeing if that resolves your issues.

**Comment by rickle-msft** [comment] 2019-11-06 18:54
As an update, we just released v12, which offers even more stability. I am going to close this issue as I believe it has been fixed in the new versions. If you need further support, please feel free to reopen or comment.

**Closed by rickle-msft** 2019-11-06 18:54 UTC
Labels: v10
