### ISSUE TITLE
CloudBlockBlob.upload() method throws exception in final block

### ISSUE THREAD

**Issue by LingtaoKong** [Azure/azure-storage-java#83] opened 2016-03-17 12:31 UTC
upload() method in CloudBlockBlock class has the below codes:
-----------------------------------------------------------
           try {
                writeStream.write(sourceStream, length);
            }
            finally {
                writeStream.close();                       // Obviously, here may be throw an IOException and the original StorageException will be aborted
            }
--------------------------------------------------------------

So, it is very difficult to get the root cause from the exception.

Thanks,
/Lingtao

**Comment by LingtaoKong** [comment] 2016-03-18 02:48
Add the call stack:
java.io.IOException
        at com.microsoft.azure.storage.core.Utility.initIOException(Utility.java:569)
        at com.microsoft.azure.storage.blob.BlobOutputStream.writeBlock(BlobOutputStream.java:444)
        at com.microsoft.azure.storage.blob.BlobOutputStream.access$000(BlobOutputStream.java:53)
        at com.microsoft.azure.storage.blob.BlobOutputStream$1.call(BlobOutputStream.java:388)
        at com.microsoft.azure.storage.blob.BlobOutputStream$1.call(BlobOutputStream.java:385)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.azure.storage.StorageException: The server is busy.
        at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:89)
        at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
        at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175)
        at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadBlockInternal(CloudBlockBlob.java:904)
        at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadBlock(CloudBlockBlob.java:876)
        at com.microsoft.azure.storage.blob.BlobOutputStream.writeBlock(BlobOutputStream.java:438)
        ... 9 more

**Comment by emgerner-msft** [comment] 2016-03-24 17:01
Taking a look at this now. Could you please add the full call stack? I could be missing it, but I don't see the finally block throw (I'm assuming it's part of the '... 9 more').

More info: The reason an IOException gets thrown instead of StorageException is because BlobOutputStream which backs the upload APIs for larger uploads implements the Java Stream interface. This interface dictates that we have to throw IOExceptions. We do wrap the StorageException in the IOException so the full info should still be there. We can still work on potentially making things clearer (which is why I want the full stack trace) but I also want to clarify why this particular exception wrapping occurs.

**Comment by LingtaoKong** [comment] 2016-03-28 11:46
Sorry, the logs were folded when output. I can tell you what happened.
The source snippet is like below:
try {
    CloudBlockBlob blob = ...;
    blob.upload(inputstream, ...); // Here, the blob server discarded this request because of its throttling,
                                                   // and, throw StorageException(The server is busy.)
} catch (StorageException e) {
   ...
} catch (IOException e) {
   ...
}

I have contacted with the storage support, they confirmed the root cause is the incorrect throttling. 
But, the exception is wrapped to IOException.

I go through the JDK sources,  the line 676 of CloudBlockBlob.java wraps the exception, but I don't think it is reasonable, because the IOException is threw then JDK releases its BlobOutputStream object internally. 
L671~677:
L671: final BlobOutputStream writeStream = this.openOutputStream(accessCondition, options, opContext);
            try {
                writeStream.write(sourceStream, length);
            }
            finally {
                writeStream.close();
            }

**Comment by emgerner-msft** [comment] 2016-03-28 16:54
Thanks for the longer description. The reason I gave above for IOException applies then. Looking at line 676 in CloudBlockBlob, it calls writeStream.close(). writeStream is a BlobOutputStream which extends the [Java OutputStream](https://docs.oracle.com/javase/7/docs/api/java/io/OutputStream.html). The methods which implement this intreface can only throw IOExceptions per the interface definition. writeStream.write at line 673 is what's actually uploading your blob, and this is also calling into the writeStream. The stream write() method also can only throw an IOException. So, writeStream.close() is not inappropriately wrapping the StorageException -- both line 673 and 676 can only throw IOExceptions in the first place.

Note from my description above that the IOExceptions thrown by these methods will wrap a StorageException. So, if you want to do some special handling, catch IOExceptions and look at the cause. Also note that upload() may still throw StorageExceptions. This is due to line 668. So, your code should simply catch *both* IOExceptions and StorageExceptions, as the upload() method contract specifies.

**Comment by LingtaoKong** [comment] 2016-03-29 02:14
Thanks for your explanation.

**Comment by emgerner-msft** [comment] 2016-03-29 21:32
Any time! Going to close this issue for now. If you have additional related questions feel free to reopen this, or to open up another issue.

**Closed by emgerner-msft** 2016-03-29 21:32 UTC
